### PR TITLE
Update todos.txt

### PR DESCRIPTION
**Pull request by kristianfreeman**
😎

### CODE REVIEW

**Review by shayk89 — APPROVED** [review]
👍

**Review by Mcorupe — APPROVED** [review]
looks good.

**Comment by maverickg59** [comment]
Great success.

**Comment by TheDavidKruse** [comment]
Eh, needs a rebase and some more thought put into it. Looks like it needs some more syntatic sugar before we can really merge it.

**Review by KGriego — COMMENTED** [review]
We need some more coffee in the todos

**Pull request merged**
